language: node_js

node_js:
  - "node"

before_install:
  - sudo apt-get update
  - sudo apt-get install autoconf libtool nasm -y

install:
  - yarn install
  - yarn run clean || exit 0

script:
  - yarn make

cache: yarn
