language: node_js

os:
- windows
- linux
- osx

node_js:
- "node"

before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install nasm -y; fi

install:
- yarn install
- yarn clean || exit 0

script:
- yarn make

cache: yarn
