language: node_js

node_js:
  - "node"

before_install:
  - sudo apt-get update
  - sudo apt-get install autoconf libtool nasm -y
install:
  - npm install
  - npm run clean || exit 0
  - wget https://github.com/gohugoio/hugo/releases/download/v0.45.1/hugo_0.45.1_Linux-64bit.deb
  - sudo dpkg -i hugo_0.45.1_Linux-64bit.deb

script:
  - npm test
  - hugo

cache: yarn
