baseURL = "https://relaxed-brown-a05637.netlify.com/"
languageCode = "en-us"
title = "CYBER SMART PANTHERS"
theme="GCI"
ignoreFiles = [ "README.md" ]
enableRobotsTXT = true
enableEmoji = true

[Params.img]
    source = "/created/img/"

[Params.header]
    enable = true

[Params.home]
    desc = "Home"

[Params.nav]
    enable = true

    [Params.nav.home]
        enable = true
        img = "/created/img/logo.jpg"
        text = ""
        alt = "CYBER SMART PANTHERS"
        title = "CYBER SMART PANTHERS: Home"
        link = "/"

    [Params.nav.menu]
        enable = true
        hamburgers = ['/created/img/hamburger_black.svg', '/created/img/hamburger_red.svg', '/created/img/hamburger_brown.svg',
                     '/created/img/hamburger_beige.svg', '/created/img/hamburger_green.svg', '/created/img/hamburger_blue.svg',
                      '/created/img/hamburger_white.svg']

        # Both values are indexs of the above array, starting at 0 and gonig to 6

        # Icon that loads with the page
        defualt = 0

        # Icon that is changed to when clicked
        active = 1

    [Params.nav.links]
        enable = true

        # Used by hugo to generate the navbar links
        # It is a 2D array,
        # First item: link text.
        # Second item: link/section id (which should always start with /# for in page links)

        #links NEED to have end slash to be maked (current) correctly
        text = [['HOME', '/'],
               ['ABOUT', '/about/'],
               ['TIPS', '/blog/'],
               ['MORE RESOURCES', '/resources/'],
               ['REPORT INCIDENT', 'https://web.chapman.edu/IncidentReport']
               ]

    [Params.nav.search]
        enable = true
        title = "Results for:  "
        close_but = "Close"
        but = "Search"


[Params.slideshow]
    enable = true
    ride = "carousel"
    interval = 5000
    keyboard = false
    pause = true

# frontpage part of blog
[Params.tips]
    title = "Become a Chapman Cyber Ninja:"
    enable = true
    read = "Read more of: "

    # In index.html
    frontpage_number = 4
    all = "READ ALL TIPS"
    link = "/blog"

# blog info here, 20 shown cap
[Params.blog]
    enable = true

    # in url.com/blog
    number = 20
    title = "All Tips"
    but = "More Tips"
    desc = "Learn more about cybersecurity"

[Params.links]
    enable = true
    title = "Resources"
    all = "SEE ALL RESOURCES"
    url = "/resources/"
    desc = "Get helpful outside resources"

    # In index.html
    frontpage_number = 5

    #in url.com/resources
    main_number = 20

[Params.about]
    title = "Meet the Team"

    [Params.profiles]
        enable = true

[Params.scripts]
    enable = true
    webpack_enable = true
    bootstrap_enable = true

[Params.footer]
    enable = true
    copyright = "©2018 Chapman University, Cyber Smart Panthers GCI Team"
    text = "Made by Jonathan Burns and Rachel Ross"
    link = "https://github.com/jhburns/3GCI"
    link_text = "Check out my work or apply for license"

    [Params.footer.license]
        enable = true

[Params.err]
    enable = true
    title = "Page Not Found"
    but = "Go Home"
    text = "The requested webpage is not found, please try a different address in the URL bar above."
    desc = "404"

    [Params.err.msg]
        tips = "Error: no tips. contact Admin to check icons, add blog, and restart hugo server"
        head = "Error: CSS not compiled, please contact Admin to restart yarn and hugo server"
        slideshow = "Error: no blogs found. Contact admin to add some and then have the Admin restart hugo server."
