baseURL = ""
languageCode = "en-us"
title = "Chapman security"
theme="GCI"
ignoreFiles = [ "README.md" ]


[Params.header]
    enable = true

[Params.nav]
    enable = true

[Params.scripts]
    enable = true
    webpack_enable = false

[Params.footer]
    enable = true
    [Params.footer.license]
        enable = false

