baseURL = "https://relaxed-keller-2816e7.netlify.com"
languageCode = "en-us"
title = "Chapman security"
theme="GCI"
ignoreFiles = [ "README.md" ]


[Params.header]
    enable = true

[Params.nav]
    enable = true

    [Params.nav.home]
        enable = true
        text = ""
        alt = "CYBER SMART PANTHERS"
        title = "CYBER SMART PANTHERS: Home"

    [Params.nav.menu]
        enable = true
        hamburgers = ['/icons/hamburger_black.svg', '/icons/hamburger_red.svg', '/icons/hamburger_brown.svg',
                     '/icons/hamburger_beige.svg', '/icons/hamburger_green.svg', '/icons/hamburger_blue.svg',
                      '/icons/hamburger_white.svg']

        # Index is which color menu is used, starting at 0 and going to 6
        # see above
        index = 0

    [Params.nav.links]
        enable = true

        # Used by hugo to generate the navbar links
        # It is a 2D array,
        # First item: link text.
        # Second item: link/section id (which should always start with /# for in page links)
        text = [['HOME', '/#'],
               ['ABOUT', '/#about'],
               ['TIPS', '/#tips'],
               ['MORE RESOURCES', '/#resources'],
               ['REPORT INCIDENT', '/#report']
               ]

[Params.scripts]
    enable = true
    webpack_enable = false
    bootstrap_enable = true


[Params.footer]
    enable = true
    [Params.footer.license]
        enable = false

