baseURL = "https://relaxed-keller-2816e7.netlify.com"
languageCode = "en-us"
title = "Chapman security"
theme="GCI"
ignoreFiles = [ "README.md" ]
enableRobotsTXT = true
enableEmoji = true

[Params.img]
    source = "created/img/"

[Params.header]
    enable = true

[Params.nav]
    enable = true

    [Params.nav.home]
        enable = true
        img = "/created/img/logo.jpeg"
        text = ""
        alt = "CYBER SMART PANTHERS"
        title = "CYBER SMART PANTHERS: Home"
        link = "/"

    [Params.nav.menu]
        enable = true
        hamburgers = ['/created/img/hamburger_black.svg', '/created/img/hamburger_red.svg', '/created/img/hamburger_brown.svg',
                     '/created/img/hamburger_beige.svg', '/created/img/hamburger_green.svg', '/created/img/hamburger_blue.svg',
                      '/created/img/hamburger_white.svg']

        # Index is which color menu is used, starting at 0 and going to 6
        # see above
        index = 0

    [Params.nav.links]
        enable = true

        # Used by hugo to generate the navbar links
        # It is a 2D array,
        # First item: link text.
        # Second item: link/section id (which should always start with /# for in page links)
        text = [['HOME', '/#'],
               ['ABOUT', '/#about'],
               ['TIPS', '/blog'],
               ['MORE RESOURCES', '/#resources'],
               ['REPORT INCIDENT', 'https://web.chapman.edu/IncidentReport']
               ]


[Params.slideshow]
    enable = true
    ride = "carousel"
    interval = 5000
    keyboard = false
    pause = true

[Params.tips]
    title = "Become a Chapman Cyber Ninja:"

[Params.blog]
    but = "More Tips"


[Params.scripts]
    enable = true
    webpack_enable = true
    bootstrap_enable = true


[Params.footer]
    enable = true
    copyright = "©2018 Chapman University, Cyber Smart Panthers GCI Team"
    text = "Made by Jonathan Burns and Rachel Ross"
    link = "https://github.com/jhburns/3GCI"
    link_text = "Check out my work or apply for license"

    [Params.footer.license]
        enable = true

[Params.err]
    enable = true
    title = "Page Not Found"
    but = "Go Home"
    text = "The requested webpage is not found, please try a different address in the URL bar above."
