removedDirectories =        ['themes/GCI/static/created',
                            'yarn-error.log', 'error.log',
                             'resources',
                            'themes/GCI/scr/img/thumbnails',
                             './build_scripts/test'
                            ]